name = "paseo-relay"
account_id = "2cb0d6b66a3ff642d924842aa0a80806"
main = "src/cloudflare-adapter.ts"
compatibility_date = "2026-05-18"

routes = [{ pattern = "relay.paseo.32r4.asia", custom_domain = true }]

[observability]
enabled = true

[[durable_objects.bindings]]
name = "RELAY"
class_name = "RelayDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RelayDurableObject"]
